/* US English */
const labels = {
  musicPlayer: 'Music Player',
  sync: 'Sync',
  settings: 'Settings',
  info: 'Info',
  about: 'About',
  addToPlaylist: 'Add To Playlist',
  addToQueue: 'Add To Queue',
  playNext: 'Play Next',
  showInfo: 'Show Info',
  addedToQueue: 'Added to queue',
  OK: 'OK',
  okay: 'Okay',
  dismiss: 'Dismiss',
  searchMusic: 'Search Music',
  playAllNext: 'Play All Next',
  addAllToPlaylist: 'Add All To Playlist',
  addAllToQueue: 'Add All To Queue',
  duration: 'Duration',
  trackInformation: 'Track Information',
  album: 'Album',
  track: 'Track',
  tracks: 'tracks',
  artist: 'Artist',
  folder: 'Folder',
  currentlyPlaying: 'Currently Playing',
  currentPlaylist: 'Current Playlist',
  songInfo: 'Song Info',
  title: 'Title',
  noTracksFound: 'No tracks found',
  shuffled: 'Shuffled',
  couldntShuffleTracks: "Couldn't shuffle tracks",
  playing: 'Playing',
  couldntPlayTracks: "Couldn't play tracks",
  fromAll: 'from all',
};

export default labels;
