/* US English */
const labels = {
  musicPlayer: 'Music Player',
  sync: 'Sync',
  settings: 'Settings',
  info: 'Info',
  appInfo: 'App Info',
  about: 'About',
  addToPlaylist: 'Add To Playlist',
  addToQueue: 'Add To Queue',
  playNext: 'Play Next',
  showInfo: 'Show Info',
  addedToQueue: 'Added to queue',
  OK: 'OK',
  okay: 'Okay',
  dismiss: 'Dismiss',
  searchMusic: 'Search Music',
  playAllNext: 'Play All Next',
  addAllToPlaylist: 'Add All To Playlist',
  addAllToQueue: 'Add All To Queue',
  duration: 'Duration',
  trackInformation: 'Track Information',
  album: 'Album',
  track: 'Track',
  tracks: 'tracks',
  artist: 'Artist',
  folder: 'Folder',
  nowPlaying: 'Now Playing',
  currentPlaylist: 'Current Playlist',
  songInfo: 'Song Info',
  title: 'Title',
  noTracksFound: 'No tracks found',
  shuffled: 'Shuffled',
  couldntShuffleTracks: "Couldn't shuffle tracks",
  playing: 'Playing',
  couldntPlayTracks: "Couldn't play tracks",
  fromAll: 'from all',
  playingSpeedReset: 'Reset playing speed',
  couldntFavSong: 'Could not set song as favorite',
  playDuration: 'Play Duration',
  markedFavorite: 'Marked Favorite',
  yes: 'Yes',
  no: 'No',
  includedInPlaylists: 'Included In Playlists',
  location: 'Location',
  noInfoFound: 'No Information Found',
  name: 'Name',
  trackCount: 'Track Count',
  playlist: 'Playlist',
  untitledPlaylist: 'Untitled Playlist',
  playlistName: 'Playlist Name',
  save: 'Save',
  shuffle: 'Shuffle',
  play: 'Play',
  playlistSubtitle: 'Select from your favorite playlists',
  searchSubtitle: 'Search within music',
  na: 'N/A',
};

export default labels;
